---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.8"

params:
  URL:

inputs:
- name: source-code

run:
  path: source-code/ci/tasks/smoke-test-trader-app.sh